services:
  bypass:
    build: ./build
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:  
      - 1panel-network 
    environment:
      DDNS_GO_HOSTS_PATH: ${DDNS_GO_HOSTS_PATH}
      DDNS_GO_HOSTS_PORT: ${DDNS_GO_HOSTS_PORT}
      DDNS_GO_HOSTS_IGNORE: ${DDNS_GO_HOSTS_IGNORE}
    command: 
      /ddns-go-hosts
    volumes:
      - "./data:/data"
    labels:
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
    
