## 
ikuai-url: http://192.168.99.2 # 爱快网页控制台登陆地址 结尾不要加 "/"，如在爱快docker内运行，网关就是爱快地址，可以不写，如不填写，则使用第一个接口的网关地址，
username: admin # ikuai username 爱快登陆用户名
password: admin888  # ikuai user password爱快登陆密码
cron: 0 7 * * * # crontab 执行更新的周期 格式为linux crontab 格式 注意时区问题，也可以用  @every 24h00m00s  表示每间隔24小时执行一次
AddErrRetryWait: 10s # 自动重试时间间隔 时间格式为 10s  120s
AddWait: 1s # 添加规则后等待时间 等待爱快反应 适合性能低的设备

ip-group:     # IP分组 和端口分流配合使用
  - name: 国内  # IP分组名称，分为多个时在名称后面拼接“序号”，如“国内_1”  因为爱快的ip分组没有备注功能，这里使用  IKUAI_BYPASS_<国内>_<01>来区分
    ## IP分组 cidr 列表网址，每行一个，超过1000行会自动分为多个，ipv6 地址会被删除
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
  - name: Telegram
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
stream-ipport:      # 端口分流，与IP分组组合使用
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan1 # 分流线路 这里默认到wan1 运营商
    src-addr: 192.168.1.10-192.168.1.254   # 分流的源地址  对应 ip-group: 国内 的目标地址
    ip-group: 国内
  - type: 1 # 分流方式：0-外网线路，1-下一跳网关
    nexthop: 192.168.1.2 # 下一跳网关  一般是openwrt地址
    src-addr: 192.168.1.10-192.168.1.254
    ip-group: Telegram

custom-isp:     # 自定义运营商  IP分流
  - name: 国内IP列表  # 自定义运营商名称
    ## 自定义运营商 cidr 列表网址，每行一个，超过5000行会自动分为多个，ipv6 地址会被删除 
    ## 下面演示规则使用了ghproxy.com的代理，如果失效请自行更换或另外想办法，建议使用https://github.com/hunshcn/gh-proxy自建
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    tag: ipcn # 规则的备注标签后缀 如果留空默认为自定义运营商名称
  - name: telegram
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
    tag: iptg
  - name: google
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
    tag: ipgoogle
  #- name: facebook
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/facebook.txt
  #  tag: ipfb
  #- name: twitter
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/twitter.txt
  #  tag: iptw
  #- name: cloudflare
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cloudflare.txt
  #  tag: ipcf
  #- name: netflix
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/netflix.txt
  #  tag: ipnf
  
stream-domain:      # 域名分流 可选功能，优先级比ip分流高
  #- interface: wan2 # 分流线路
  #  src-addr: 192.168.1.10-192.168.1.254    # 分流的源地址 多ip段用“,”分开 参考 https://github.com/joyanhui/ikuai-bypass/issues/1#issuecomment-1892763993
  #  ## 域名列表网址，每行一个，超过1000行会自动分为多个
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt
  # 下面是强制走wan2的
  - interface: wan2
    src-addr: 192.168.1.10-192.168.1.254
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    tag: gfw
  - interface: wan2
    src-addr: 192.168.1.10-192.168.1.254
    # 作者自己维护的自定义的域名列表 强制走代理的域名
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/bypass-domain-list.txt
    tag: private_bypass
  # 下面是自动走wan1直连的，
  - interface: wan1
    src-addr: 192.168.1.10-192.168.1.254
    # 作者自己维护的自定义的域名列表 主要存放github的镜像网站等国内可以直连的镜像或其他类型域名
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/direct-domain-list.txt
    tag: private_direct
  #- interface: wan1
  #  src-addr: 192.168.1.10-192.168.1.254 
  #  china-list 网址列表较大，不建议启用,在部分ikuai设备上可能会导致维护的时候超时出错。
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
  #  tag: cn
  #- interface: wan1
  #  src-addr: 192.168.1.10-192.168.1.254 
  #  url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt
  #  tag: apple
  #  下面是去广告的
  #  todo 以后会使用爱快的域名黑名单模式来实现广告过滤，暂时用线路分流功能屏蔽
  #  wan99是一个不可用或者不通的线路。因为reject-list网址列表较大，如爱快性能不佳不建议启用。
  #- interface: wan99
  #  src-addr: 192.168.1.10-192.168.1.254 
  #  url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
  #  tag: adFilter
