services:
  bypass:
    build: ./build
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:  
      - 1panel-network 
    environment:
      CONFIG_FILE_PATH: ${CONFIG_FILE_PATH}
    command: 
      /ikuai-bypass -c ${CONFIG_FILE_PATH} -r cronAft
    volumes:
      - "./conf:/conf"
    labels:
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
    
