services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116 # 自定义 hbbs 映射端口
      - 21116:21116/udp # 自定义 hbbs 映射端口
      - 21118:21118 # web client
    image: rustdesk/rustdesk-server
    command: hbbs -r ${SERVER_HOST}:21117 -k ${SERVER_KEY} # 填入个人域名或 IP + hbbr 暴露端口
    volumes:
      - ./data:/root # 自定义挂载目录
    networks:
      - 1panel-network
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117 # 自定义 hbbr 映射端口
      - 21119:21119 # web client
    image: rustdesk/rustdesk-server
    command: hbbr -k ${SERVER_KEY}
    volumes:
      - ./data:/root
    networks:
      - 1panel-network
    restart: always

  rustdesk-api:
    container_name: rustdesk-api
    restart: always
    networks:
      - 1panel-network
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=${SERVER_HOST}:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=${SERVER_HOST}:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://${SERVER_HOST}:21114
      - RUSTDESK_API_RUSTDESK_KEY=${SERVER_KEY}
    ports:
      - 21114:21114
    image: lejianwen/rustdesk-api:v2.4.6.10
    volumes:
      - "./data-api:/app/data"
    depends_on:
      - hbbr
      - hbbs
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
